name: AtividadeSomativa1-pipeline

image: python

stages:
  - build
  - test
  - deploy

# Etapa de build: Copia arquivos de HTML para a pasta de saída
build_job:
  stage: build
  script:
    - echo "Construindo a aplicação..."
    - mkdir -p dist
    - cp index.html dist/  # Copia o arquivo index.html para a pasta dist
  artifacts:
    paths:
      - dist/  # Pasta de saída com os arquivos HTML

# Etapa de test: Verifica se o arquivo index.html existe na pasta dist
test_job:
  stage: test
  script:
    - echo "Verificando a existência do arquivo index.html..."
    - test -f dist/index.html && echo "Test passed: index.html exists." || echo "Test failed: index.html does not exist."
  only:
    - merge_requests  # Executa a etapa de teste apenas em solicitações de mesclagem (MRs)

# Etapa de deploy: Faz o deploy dos arquivos HTML
deploy_job:
  stage: deploy
  script:
    - echo "Fazendo deploy da aplicação..."
    # Adicione comandos para fazer o deploy da aplicação, como enviar os arquivos HTML para um servidor
    - echo "Deploy concluído"
  only:
    - master  # Executa a etapa de deploy apenas na branch master
